model_params:
  model: DeepLab
  backbone: resnet50_gn_ws
  num_classes: 1


args:
  expdir: "src2"
  logdir: &logdir "./logs/structseg"
  baselogdir: "./logs/structseg"

distributed_params:
  opt_level: O1

stages:

  state_params:
    main_metric: &reduce_metric dice
    minimize_metric: False

  criterion_params:
    criterion: DiceLoss

  data_params:
    batch_size: 16
    num_workers: 4
    drop_last: False
    # drop_last: True

    image_size: &image_size 512
    train_csv: "./csv/train_0.csv"
    valid_csv: "./csv/valid_0.csv"
    data_csv: "../Lung_GTV_2d/data.csv"

  stage1:

    optimizer_params:
      optimizer: Adam
      lr: 0.0001

    scheduler_params:
      scheduler: OneCycleLR
      num_steps: &num_epochs 100
      lr_range: [0.0005, 0.00001]
      warmup_steps: 5
      momentum_range: [0.85, 0.95]

    state_params:
      num_epochs: 100

    callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
        accumulation_steps: 2
      dice:
        callback: DiceCallback
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
        # mode: 'batch'
      saver:
        callback: CheckpointCallback